# Generated by Django 4.1.1 on 2022-10-01 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.PositiveIntegerField()),
                ('Answer', models.PositiveIntegerField(null=True)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Hint', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodeFinds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.PositiveIntegerField(null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treasurehunt.code')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
