# Generated by Django 4.1.1 on 2022-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0002_rename_codefinds_codefind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='code',
            name='Longitude',
        ),
        migrations.AddField(
            model_name='code',
            name='HintType',
            field=models.SmallIntegerField(choices=[(1, 'Pointer'), (2, 'Digit')], default=1),
        ),
        migrations.AddField(
            model_name='code',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='code',
            name='Hint',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='code',
            name='Order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
