# Generated by Django 4.0.6 on 2022-10-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0004_alter_code_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='Answer',
            new_name='AnswerDigit',
        ),
        migrations.AddField(
            model_name='code',
            name='AnswerLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
