# Generated by Django 4.0.6 on 2022-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0005_rename_answer_code_answerdigit_code_answerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='AnswerDigit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
