# Generated by Django 4.1.1 on 2022-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0006_alter_code_answerdigit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='Location',
            new_name='LocationDescription',
        ),
        migrations.AddField(
            model_name='code',
            name='Latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='code',
            name='Longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
